# Generated by Django 3.1.1 on 2020-09-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skateboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
