# Generated by Django 3.1.1 on 2020-10-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skateboarders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skateboard',
            name='stance',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
