# Generated by Django 3.1.1 on 2020-10-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skateboarders', '0002_skateboard_stance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skateboard',
            name='stance',
            field=models.CharField(default='regular', max_length=8),
            preserve_default=False,
        ),
    ]
